#!/bin/sh
filepath=~/.cache/zsh/history
echo "Initial History Count"
wc -l < "$filepath"
awk '!x[$0]++' < "$filepath" > /tmp/histemp
cat /tmp/histemp > "$filepath" 
echo "Final History Count"
wc -l < "$filepath"
