#!/bin/bash


boidfile=~/.secrets/.boid.txt
echo ""
echo "================== All IPOS ================="
echo ""
totalIpos=$(curl -4 -s 'https://iporesult.cdsc.com.np/result/companyShares/fileUploaded' \
  -H 'Accept: application/json, text/plain, */*' \
  --compressed  | jq [.body])
echo $totalIpos | jq . 


boidline=$(tail -n 1 $boidfile)
boid=$(echo $boidline | awk '{print $2}')
name=$(echo $boidline | awk '{print $1}')


read -p "Select Company Id : " id
#echo $totalIpos | jq .0
echo ""
echo "=================== $name ===================="
echo ""
#read -p "Boid : " boid
curl -4 -s 'https://iporesult.cdsc.com.np/result/result/check' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Content-Type: application/json' \
  --data-raw '{"companyShareId":"'$id'","boid":"'$boid'"}' \
  --compressed | jq
